language: node_js
node_js:
- "node"
cache: npm
script: npm run deploy
after_script: npm run alias
env:
global:
  secure: "lOq3UWCtaqRykUGFv6c/p0bN7eXd9BCHcTDYF0RfY5lIH7O0R77O0roktI63EWIAkjujlD8IvB7ceYJwAZtATA8613rVk3z4I18C7v7mH8QQBxeF+ye2+96c359jIfOzqx5a4ArDaYyxAQr4j9h2mK3J86Uw1xGAdpFHzZPv8D5QALtzIljXdCOHfl8fRF65XFKi2EBYrehsdrPA+1KhQs+EDJZtV646GI1a/KCjqWBU85EldHcWmkcNC2Q3qbFVkPRYXWK5tPrvzNkGJTbAe/NfYNMd7QhgxFg3HFXzYtkNXDfL9VoqN6ybQeNdFNBhK5Z8EDgnkjJt6DpFW4NzIaKYBebCQuPbj+7W0eGQPrbnYTEtTGSSnR014Xb6k+AfyTPwt5t4WN0P9oZ86TJl1Tq7UiX2G5YcZTI+l/7B/D6p255aTgGm7RXt+nFJTU0PkRfYkdhmk95zgsICDqPGzaMj8+IRJSgljsA3mNl6wJ7iJ6ibrt+IroSh8cdaBrFFugpuHoH6hwGJpfXVDIpxhOEqUNgTSV+w2TPV8HecTBugAkFIPdBCyFIm3axse2eVTZAc+zbufVbTEhbi9897A7hTLZvExk11zV2dtIe2GsosTjMDbiy5lGWOYJMoyyNkU9/K1dmRWshoST+Zjuql7MgqJPnIoywH2d2Z3Q3YTvM="